name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.103

      - name: Build solution
        run: |
          git submodule update --init --recursive
          dotnet restore Responses.sln
          dotnet build -c Release Responses/Responses.csproj

      - name: Run unit tests
        run: |
          dotnet test test/Responses.Tests/Responses.Tests.csproj

      - name: Generate NuGet package
        run: |
          dotnet pack -c Release
      
      - name: Generate push NuGet package
        run: |
          dir Responses\bin\Release\*.nupkg
          dir /s/b Responses\bin\Release\*.nupkg | xargs -i dotnet nuget push {} -k ${{ secrets.nuget_token }} -s https://api.nuget.org/v3/index.json 
          
      - name: Install NuGet client
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Add private GitHub registry to NuGet
        run: |
          nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/slipalison/index.json -Username slipalison -Password ${{ secrets.GITHUB_TOKEN }}

      - name: Push generated package to GitHub registry
        run: |
          dir Responses\bin\Release\*.nupkg
          nuget push Responses\bin\Release\*.nupkg -Source "GPR" -SkipDuplicate
